// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_maglev__MagLev_MagLevType_Impl_
#include <maglev/_MagLev/MagLevType_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_112__new,"maglev._MagLev.MagLevType_Impl_","_new",0x128473c2,"maglev._MagLev.MagLevType_Impl_._new","maglev/MagLev.hx",112,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_103_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",103,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_104_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",104,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_105_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",105,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_106_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",106,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_107_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",107,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_108_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",108,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_109_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",109,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_110_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",110,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_6a0f100a412edb16_111_boot,"maglev._MagLev.MagLevType_Impl_","boot",0x1480e293,"maglev._MagLev.MagLevType_Impl_.boot","maglev/MagLev.hx",111,0x5b19476f)
namespace maglev{
namespace _MagLev{

void MagLevType_Impl__obj::__construct() { }

Dynamic MagLevType_Impl__obj::__CreateEmpty() { return new MagLevType_Impl__obj; }

void *MagLevType_Impl__obj::_hx_vtable = 0;

Dynamic MagLevType_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< MagLevType_Impl__obj > _hx_result = new MagLevType_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool MagLevType_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x356ec803;
}

int MagLevType_Impl__obj::MagLevType_Result;

int MagLevType_Impl__obj::MagLevType_Error;

int MagLevType_Impl__obj::MagLevType_Function;

int MagLevType_Impl__obj::MagLevType_Object;

int MagLevType_Impl__obj::MagLevType_Array;

int MagLevType_Impl__obj::MagLevType_Number;

int MagLevType_Impl__obj::MagLevType_String;

int MagLevType_Impl__obj::MagLevType_Boolean;

int MagLevType_Impl__obj::MagLevType_Null;

int MagLevType_Impl__obj::_new(int i){
            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_112__new)
HXDLIN( 112)		int this1 = i;
HXDLIN( 112)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(MagLevType_Impl__obj,_new,return )


MagLevType_Impl__obj::MagLevType_Impl__obj()
{
}

bool MagLevType_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *MagLevType_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo MagLevType_Impl__obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Result,HX_("MagLevType_Result",18,90,b8,1e)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Error,HX_("MagLevType_Error",ed,a4,93,f9)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Function,HX_("MagLevType_Function",13,57,4b,3d)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Object,HX_("MagLevType_Object",fa,a5,73,2b)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Array,HX_("MagLevType_Array",be,46,f9,ab)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Number,HX_("MagLevType_Number",04,ae,ae,b7)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_String,HX_("MagLevType_String",0c,50,64,27)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Boolean,HX_("MagLevType_Boolean",0d,17,6d,d5)},
	{::hx::fsInt,(void *) &MagLevType_Impl__obj::MagLevType_Null,HX_("MagLevType_Null",02,f1,2c,5d)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void MagLevType_Impl__obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Result,"MagLevType_Result");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Error,"MagLevType_Error");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Function,"MagLevType_Function");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Object,"MagLevType_Object");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Array,"MagLevType_Array");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Number,"MagLevType_Number");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_String,"MagLevType_String");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Boolean,"MagLevType_Boolean");
	HX_MARK_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Null,"MagLevType_Null");
};

#ifdef HXCPP_VISIT_ALLOCS
static void MagLevType_Impl__obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Result,"MagLevType_Result");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Error,"MagLevType_Error");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Function,"MagLevType_Function");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Object,"MagLevType_Object");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Array,"MagLevType_Array");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Number,"MagLevType_Number");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_String,"MagLevType_String");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Boolean,"MagLevType_Boolean");
	HX_VISIT_MEMBER_NAME(MagLevType_Impl__obj::MagLevType_Null,"MagLevType_Null");
};

#endif

::hx::Class MagLevType_Impl__obj::__mClass;

static ::String MagLevType_Impl__obj_sStaticFields[] = {
	HX_("MagLevType_Result",18,90,b8,1e),
	HX_("MagLevType_Error",ed,a4,93,f9),
	HX_("MagLevType_Function",13,57,4b,3d),
	HX_("MagLevType_Object",fa,a5,73,2b),
	HX_("MagLevType_Array",be,46,f9,ab),
	HX_("MagLevType_Number",04,ae,ae,b7),
	HX_("MagLevType_String",0c,50,64,27),
	HX_("MagLevType_Boolean",0d,17,6d,d5),
	HX_("MagLevType_Null",02,f1,2c,5d),
	HX_("_new",61,15,1f,3f),
	::String(null())
};

void MagLevType_Impl__obj::__register()
{
	MagLevType_Impl__obj _hx_dummy;
	MagLevType_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("maglev._MagLev.MagLevType_Impl_",ad,9d,4d,85);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &MagLevType_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = MagLevType_Impl__obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(MagLevType_Impl__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< MagLevType_Impl__obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = MagLevType_Impl__obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = MagLevType_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = MagLevType_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void MagLevType_Impl__obj::__boot()
{
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_103_boot)
HXDLIN( 103)			int this1 = 11;
HXDLIN( 103)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_103_boot)
HXDLIN( 103)		MagLevType_Result = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_104_boot)
HXDLIN( 104)			int this1 = 10;
HXDLIN( 104)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_104_boot)
HXDLIN( 104)		MagLevType_Error = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_105_boot)
HXDLIN( 105)			int this1 = 20;
HXDLIN( 105)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_105_boot)
HXDLIN( 105)		MagLevType_Function = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_106_boot)
HXDLIN( 106)			int this1 = 5;
HXDLIN( 106)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_106_boot)
HXDLIN( 106)		MagLevType_Object = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_107_boot)
HXDLIN( 107)			int this1 = 4;
HXDLIN( 107)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_107_boot)
HXDLIN( 107)		MagLevType_Array = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_108_boot)
HXDLIN( 108)			int this1 = 3;
HXDLIN( 108)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_108_boot)
HXDLIN( 108)		MagLevType_Number = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_109_boot)
HXDLIN( 109)			int this1 = 2;
HXDLIN( 109)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_109_boot)
HXDLIN( 109)		MagLevType_String = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_110_boot)
HXDLIN( 110)			int this1 = 1;
HXDLIN( 110)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_110_boot)
HXDLIN( 110)		MagLevType_Boolean = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		int _hx_run(){
            			HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_111_boot)
HXDLIN( 111)			int this1 = 0;
HXDLIN( 111)			return this1;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_6a0f100a412edb16_111_boot)
HXDLIN( 111)		MagLevType_Null = ( (int)( ::Dynamic(new _hx_Closure_0())()) );
            	}
}

} // end namespace maglev
} // end namespace _MagLev
