// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_maglev_MagLevAny
#include <maglev/MagLevAny.h>
#endif
#ifndef INCLUDED_maglev_MagLevArray
#include <maglev/MagLevArray.h>
#endif
#ifndef INCLUDED_maglev_MagLevNull
#include <maglev/MagLevNull.h>
#endif
#ifndef INCLUDED_maglev_MagLevObject
#include <maglev/MagLevObject.h>
#endif
#ifndef INCLUDED_maglev_MagLevString
#include <maglev/MagLevString.h>
#endif
#ifndef INCLUDED_maglev__MagLevTypes_MagLevType_Impl_
#include <maglev/_MagLevTypes/MagLevType_Impl_.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_225_new,"maglev.MagLevObject","new",0x0f4b80bf,"maglev.MagLevObject.new","maglev/MagLevTypes.hx",225,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_230_clear,"maglev.MagLevObject","clear",0xc8e737ac,"maglev.MagLevObject.clear","maglev/MagLevTypes.hx",230,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_233_exists,"maglev.MagLevObject","exists",0xb9a1b2dd,"maglev.MagLevObject.exists","maglev/MagLevTypes.hx",233,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_236_get,"maglev.MagLevObject","get",0x0f4630f5,"maglev.MagLevObject.get","maglev/MagLevTypes.hx",236,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_238_keys,"maglev.MagLevObject","keys",0x50c984b5,"maglev.MagLevObject.keys","maglev/MagLevTypes.hx",238,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_246_remove,"maglev.MagLevObject","remove",0xfe4a3145,"maglev.MagLevObject.remove","maglev/MagLevTypes.hx",246,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_249_set,"maglev.MagLevObject","set",0x0f4f4c01,"maglev.MagLevObject.set","maglev/MagLevTypes.hx",249,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_252_getStringMap,"maglev.MagLevObject","getStringMap",0x3f449a96,"maglev.MagLevObject.getStringMap","maglev/MagLevTypes.hx",252,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_255_getType,"maglev.MagLevObject","getType",0xaf2c6e4f,"maglev.MagLevObject.getType","maglev/MagLevTypes.hx",255,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_258_isEqual,"maglev.MagLevObject","isEqual",0x9ea93f49,"maglev.MagLevObject.isEqual","maglev/MagLevTypes.hx",258,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_283_toJson,"maglev.MagLevObject","toJson",0x75e34244,"maglev.MagLevObject.toJson","maglev/MagLevTypes.hx",283,0x03b0b9b4)
HX_LOCAL_STACK_FRAME(_hx_pos_044f15e1e4ee8cb8_223_create,"maglev.MagLevObject","create",0x75d0fbfd,"maglev.MagLevObject.create","maglev/MagLevTypes.hx",223,0x03b0b9b4)
namespace maglev{

void MagLevObject_obj::__construct(){
            	HX_GC_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_225_new)
HXLINE( 226)		this->values =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 227)		super::__construct();
            	}

Dynamic MagLevObject_obj::__CreateEmpty() { return new MagLevObject_obj; }

void *MagLevObject_obj::_hx_vtable = 0;

Dynamic MagLevObject_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< MagLevObject_obj > _hx_result = new MagLevObject_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool MagLevObject_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x0e9b8ca7) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x0e9b8ca7;
	} else {
		return inClassId==(int)0x7fdb9bc4;
	}
}

void MagLevObject_obj::clear(){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_230_clear)
HXDLIN( 230)		this->values->clear();
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevObject_obj,clear,(void))

bool MagLevObject_obj::exists(::String key){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_233_exists)
HXDLIN( 233)		return this->values->exists(key);
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevObject_obj,exists,return )

 ::maglev::MagLevAny MagLevObject_obj::get(::String key){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_236_get)
HXDLIN( 236)		return ::maglev::MagLevNull_obj::wrap(( ( ::maglev::MagLevAny)(this->values->get(key)) ));
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevObject_obj,get,return )

 ::maglev::MagLevArray MagLevObject_obj::keys(){
            	HX_GC_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_238_keys)
HXLINE( 239)		 ::maglev::MagLevArray arr =  ::maglev::MagLevArray_obj::__alloc( HX_CTX );
HXLINE( 240)		{
HXLINE( 240)			 ::Dynamic k = this->values->keys();
HXDLIN( 240)			while(( (bool)(k->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 240)				::String k1 = ( (::String)(k->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 241)				arr->push( ::maglev::MagLevString_obj::__alloc( HX_CTX ,k1));
            			}
            		}
HXLINE( 243)		return arr;
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevObject_obj,keys,return )

bool MagLevObject_obj::remove(::String key){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_246_remove)
HXDLIN( 246)		return this->values->remove(key);
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevObject_obj,remove,return )

void MagLevObject_obj::set(::String key, ::maglev::MagLevAny value){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_249_set)
HXDLIN( 249)		::Dynamic this1 = this->values;
HXDLIN( 249)		( ( ::haxe::ds::StringMap)(this1) )->set(key,::maglev::MagLevNull_obj::wrap(value));
            	}


HX_DEFINE_DYNAMIC_FUNC2(MagLevObject_obj,set,(void))

 ::haxe::ds::StringMap MagLevObject_obj::getStringMap(){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_252_getStringMap)
HXDLIN( 252)		return this->values;
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevObject_obj,getStringMap,return )

int MagLevObject_obj::getType(){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_255_getType)
HXDLIN( 255)		return ::maglev::_MagLevTypes::MagLevType_Impl__obj::MagLevType_Object;
            	}


bool MagLevObject_obj::isEqual( ::maglev::MagLevAny other){
            	HX_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_258_isEqual)
HXDLIN( 258)		int _hx_tmp = other->getType();
HXDLIN( 258)		if ((_hx_tmp == this->getType())) {
HXLINE( 259)			 ::maglev::MagLevObject obj = ::hx::TCast<  ::maglev::MagLevObject >::cast(other);
HXLINE( 260)			{
HXLINE( 260)				 ::Dynamic key = this->values->keys();
HXDLIN( 260)				while(( (bool)(key->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 260)					::String key1 = ( (::String)(key->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 261)					bool found = false;
HXLINE( 262)					bool equal = false;
HXLINE( 263)					{
HXLINE( 263)						 ::Dynamic key2 = obj->getStringMap()->keys();
HXDLIN( 263)						while(( (bool)(key2->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 263)							::String key21 = ( (::String)(key2->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 264)							if ((key1 == key21)) {
HXLINE( 265)								found = true;
HXLINE( 266)								 ::maglev::MagLevAny val = ( ( ::maglev::MagLevAny)(this->values->get(key1)) );
HXLINE( 267)								 ::maglev::MagLevAny val2 = ( ( ::maglev::MagLevAny)(obj->values->get(key21)) );
HXLINE( 268)								if (val->isEqual(val2)) {
HXLINE( 269)									equal = true;
            								}
            							}
            						}
            					}
HXLINE( 273)					bool _hx_tmp;
HXDLIN( 273)					if (found) {
HXLINE( 273)						_hx_tmp = !(equal);
            					}
            					else {
HXLINE( 273)						_hx_tmp = true;
            					}
HXDLIN( 273)					if (_hx_tmp) {
HXLINE( 274)						return false;
            					}
            				}
            			}
HXLINE( 277)			return true;
            		}
            		else {
HXLINE( 280)			return false;
            		}
HXLINE( 258)		return false;
            	}


 ::maglev::MagLevString MagLevObject_obj::toJson(){
            	HX_GC_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_283_toJson)
HXLINE( 284)		::String s = HX_("{",7b,00,00,00);
HXLINE( 285)		bool first = true;
HXLINE( 286)		{
HXLINE( 286)			 ::Dynamic key = this->values->keys();
HXDLIN( 286)			while(( (bool)(key->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 286)				::String key1 = ( (::String)(key->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 287)				if (!(first)) {
HXLINE( 288)					s = (s + HX_(", ",74,26,00,00));
            				}
HXLINE( 290)				s = (s + key1);
HXLINE( 291)				s = (s + HX_(": ",a6,32,00,00));
HXLINE( 292)				s = (s + ::Std_obj::string(( ( ::maglev::MagLevAny)(this->values->get(key1)) )->toJson()));
HXLINE( 293)				first = false;
            			}
            		}
HXLINE( 295)		s = (s + HX_("}",7d,00,00,00));
HXLINE( 296)		return  ::maglev::MagLevString_obj::__alloc( HX_CTX ,s);
            	}


 ::maglev::MagLevObject MagLevObject_obj::create(){
            	HX_GC_STACKFRAME(&_hx_pos_044f15e1e4ee8cb8_223_create)
HXDLIN( 223)		return  ::maglev::MagLevObject_obj::__alloc( HX_CTX );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(MagLevObject_obj,create,return )


::hx::ObjectPtr< MagLevObject_obj > MagLevObject_obj::__new() {
	::hx::ObjectPtr< MagLevObject_obj > __this = new MagLevObject_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< MagLevObject_obj > MagLevObject_obj::__alloc(::hx::Ctx *_hx_ctx) {
	MagLevObject_obj *__this = (MagLevObject_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(MagLevObject_obj), true, "maglev.MagLevObject"));
	*(void **)__this = MagLevObject_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

MagLevObject_obj::MagLevObject_obj()
{
}

void MagLevObject_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(MagLevObject);
	HX_MARK_MEMBER_NAME(values,"values");
	HX_MARK_END_CLASS();
}

void MagLevObject_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(values,"values");
}

::hx::Val MagLevObject_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		if (HX_FIELD_EQ(inName,"set") ) { return ::hx::Val( set_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"keys") ) { return ::hx::Val( keys_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"clear") ) { return ::hx::Val( clear_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"values") ) { return ::hx::Val( values ); }
		if (HX_FIELD_EQ(inName,"exists") ) { return ::hx::Val( exists_dyn() ); }
		if (HX_FIELD_EQ(inName,"remove") ) { return ::hx::Val( remove_dyn() ); }
		if (HX_FIELD_EQ(inName,"toJson") ) { return ::hx::Val( toJson_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"getType") ) { return ::hx::Val( getType_dyn() ); }
		if (HX_FIELD_EQ(inName,"isEqual") ) { return ::hx::Val( isEqual_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"getStringMap") ) { return ::hx::Val( getStringMap_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool MagLevObject_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"create") ) { outValue = create_dyn(); return true; }
	}
	return false;
}

::hx::Val MagLevObject_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"values") ) { values=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void MagLevObject_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("values",e2,03,b7,4f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo MagLevObject_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(MagLevObject_obj,values),HX_("values",e2,03,b7,4f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *MagLevObject_obj_sStaticStorageInfo = 0;
#endif

static ::String MagLevObject_obj_sMemberFields[] = {
	HX_("values",e2,03,b7,4f),
	HX_("clear",8d,71,5b,48),
	HX_("exists",dc,1d,e0,bf),
	HX_("get",96,80,4e,00),
	HX_("keys",f4,e1,06,47),
	HX_("remove",44,9c,88,04),
	HX_("set",a2,9b,57,00),
	HX_("getStringMap",d5,ce,0f,d7),
	HX_("getType",70,a2,8b,1f),
	HX_("isEqual",6a,73,08,0f),
	HX_("toJson",43,ad,21,7c),
	::String(null()) };

::hx::Class MagLevObject_obj::__mClass;

static ::String MagLevObject_obj_sStaticFields[] = {
	HX_("create",fc,66,0f,7c),
	::String(null())
};

void MagLevObject_obj::__register()
{
	MagLevObject_obj _hx_dummy;
	MagLevObject_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("maglev.MagLevObject",4d,b5,b6,80);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &MagLevObject_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(MagLevObject_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(MagLevObject_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< MagLevObject_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = MagLevObject_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = MagLevObject_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace maglev
