// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_maglev_MagLevAny
#include <maglev/MagLevAny.h>
#endif
#ifndef INCLUDED_maglev_MagLevArray
#include <maglev/MagLevArray.h>
#endif
#ifndef INCLUDED_maglev_MagLevNull
#include <maglev/MagLevNull.h>
#endif
#ifndef INCLUDED_maglev_MagLevString
#include <maglev/MagLevString.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_25210d59b9897ae1_424_new,"maglev.MagLevArray","new",0x659f253d,"maglev.MagLevArray.new","maglev/MagLev.hx",424,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_429_size,"maglev.MagLevArray","size",0x88f28d44,"maglev.MagLevArray.size","maglev/MagLev.hx",429,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_432_pop,"maglev.MagLevArray","pop",0x65a0b26e,"maglev.MagLevArray.pop","maglev/MagLev.hx",432,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_434_push,"maglev.MagLevArray","push",0x86fffe5d,"maglev.MagLevArray.push","maglev/MagLev.hx",434,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_439_shift,"maglev.MagLevArray","shift",0x4a92f29f,"maglev.MagLevArray.shift","maglev/MagLev.hx",439,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_442_unshift,"maglev.MagLevArray","unshift",0xc7c76ae6,"maglev.MagLevArray.unshift","maglev/MagLev.hx",442,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_445_reverse,"maglev.MagLevArray","reverse",0x6a0fc07f,"maglev.MagLevArray.reverse","maglev/MagLev.hx",445,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_448_get,"maglev.MagLevArray","get",0x6599d573,"maglev.MagLevArray.get","maglev/MagLev.hx",448,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_451_set,"maglev.MagLevArray","set",0x65a2f07f,"maglev.MagLevArray.set","maglev/MagLev.hx",451,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_454_getType,"maglev.MagLevArray","getType",0x6e9f29cd,"maglev.MagLevArray.getType","maglev/MagLev.hx",454,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_460_isEqual,"maglev.MagLevArray","isEqual",0x5e1bfac7,"maglev.MagLevArray.isEqual","maglev/MagLev.hx",460,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_483_toJson,"maglev.MagLevArray","toJson",0x4fb70086,"maglev.MagLevArray.toJson","maglev/MagLev.hx",483,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_422_create,"maglev.MagLevArray","create",0x4fa4ba3f,"maglev.MagLevArray.create","maglev/MagLev.hx",422,0x5b19476f)
HX_LOCAL_STACK_FRAME(_hx_pos_25210d59b9897ae1_457_getStaticType,"maglev.MagLevArray","getStaticType",0x576631db,"maglev.MagLevArray.getStaticType","maglev/MagLev.hx",457,0x5b19476f)
namespace maglev{

void MagLevArray_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_424_new)
HXLINE( 425)		this->values = ::Array_obj< ::Dynamic>::__new();
HXLINE( 426)		super::__construct();
            	}

Dynamic MagLevArray_obj::__CreateEmpty() { return new MagLevArray_obj; }

void *MagLevArray_obj::_hx_vtable = 0;

Dynamic MagLevArray_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< MagLevArray_obj > _hx_result = new MagLevArray_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool MagLevArray_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x48ac5325) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x48ac5325;
	} else {
		return inClassId==(int)0x7fdb9bc4;
	}
}

int MagLevArray_obj::size(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_429_size)
HXDLIN( 429)		return this->values->length;
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,size,return )

 ::maglev::MagLevAny MagLevArray_obj::pop(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_432_pop)
HXDLIN( 432)		return ::maglev::MagLevNull_obj::wrap(this->values->pop().StaticCast<  ::maglev::MagLevAny >());
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,pop,return )

int MagLevArray_obj::push( ::maglev::MagLevAny x){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_434_push)
HXLINE( 435)		this->values->push(x);
HXLINE( 436)		return this->size();
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevArray_obj,push,return )

 ::maglev::MagLevAny MagLevArray_obj::shift(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_439_shift)
HXDLIN( 439)		return ::maglev::MagLevNull_obj::wrap(this->values->shift().StaticCast<  ::maglev::MagLevAny >());
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,shift,return )

void MagLevArray_obj::unshift( ::maglev::MagLevAny x){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_442_unshift)
HXDLIN( 442)		::Array< ::Dynamic> _hx_tmp = this->values;
HXDLIN( 442)		_hx_tmp->unshift(::maglev::MagLevNull_obj::wrap(x));
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevArray_obj,unshift,(void))

void MagLevArray_obj::reverse(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_445_reverse)
HXDLIN( 445)		this->values->reverse();
            	}


HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,reverse,(void))

 ::maglev::MagLevAny MagLevArray_obj::get(int i){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_448_get)
HXDLIN( 448)		return ::maglev::MagLevNull_obj::wrap(this->values->__get(i).StaticCast<  ::maglev::MagLevAny >());
            	}


HX_DEFINE_DYNAMIC_FUNC1(MagLevArray_obj,get,return )

void MagLevArray_obj::set(int i, ::maglev::MagLevAny value){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_451_set)
HXDLIN( 451)		this->values[i] = ::maglev::MagLevNull_obj::wrap(value);
            	}


HX_DEFINE_DYNAMIC_FUNC2(MagLevArray_obj,set,(void))

int MagLevArray_obj::getType(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_454_getType)
HXDLIN( 454)		return 5;
            	}


bool MagLevArray_obj::isEqual( ::maglev::MagLevAny other){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_460_isEqual)
HXDLIN( 460)		int _hx_tmp = other->getType();
HXDLIN( 460)		if ((_hx_tmp == this->getType())) {
HXLINE( 461)			 ::maglev::MagLevArray o = ::hx::TCast<  ::maglev::MagLevArray >::cast(other);
HXLINE( 462)			int _hx_tmp = this->size();
HXDLIN( 462)			if ((_hx_tmp == o->size())) {
HXLINE( 463)				 ::maglev::MagLevArray arr = ::hx::TCast<  ::maglev::MagLevArray >::cast(other);
HXLINE( 464)				{
HXLINE( 464)					int _g = 0;
HXDLIN( 464)					::Array< ::Dynamic> _g1 = this->values;
HXDLIN( 464)					while((_g < _g1->length)){
HXLINE( 464)						 ::maglev::MagLevAny item = _g1->__get(_g).StaticCast<  ::maglev::MagLevAny >();
HXDLIN( 464)						_g = (_g + 1);
HXLINE( 465)						bool found = false;
HXLINE( 466)						{
HXLINE( 466)							int _g2 = 0;
HXDLIN( 466)							::Array< ::Dynamic> _g3 = arr->values;
HXDLIN( 466)							while((_g2 < _g3->length)){
HXLINE( 466)								 ::maglev::MagLevAny item2 = _g3->__get(_g2).StaticCast<  ::maglev::MagLevAny >();
HXDLIN( 466)								_g2 = (_g2 + 1);
HXLINE( 467)								if (item->isEqual(item2)) {
HXLINE( 468)									found = true;
            								}
            							}
            						}
HXLINE( 471)						if (!(found)) {
HXLINE( 471)							return false;
            						}
            					}
            				}
HXLINE( 473)				return true;
            			}
            			else {
HXLINE( 476)				return false;
            			}
            		}
            		else {
HXLINE( 480)			return false;
            		}
HXLINE( 460)		return false;
            	}


 ::maglev::MagLevString MagLevArray_obj::toJson(){
            	HX_GC_STACKFRAME(&_hx_pos_25210d59b9897ae1_483_toJson)
HXLINE( 484)		::String s = HX_("[",5b,00,00,00);
HXLINE( 485)		bool first = true;
HXLINE( 486)		{
HXLINE( 486)			int _g = 0;
HXDLIN( 486)			::Array< ::Dynamic> _g1 = this->values;
HXDLIN( 486)			while((_g < _g1->length)){
HXLINE( 486)				 ::maglev::MagLevAny item = _g1->__get(_g).StaticCast<  ::maglev::MagLevAny >();
HXDLIN( 486)				_g = (_g + 1);
HXLINE( 487)				if (!(first)) {
HXLINE( 488)					s = (s + HX_(", ",74,26,00,00));
            				}
HXLINE( 490)				s = (s + item->toJson()->getString());
HXLINE( 491)				first = false;
            			}
            		}
HXLINE( 493)		s = (s + HX_("]",5d,00,00,00));
HXLINE( 494)		return  ::maglev::MagLevString_obj::__alloc( HX_CTX ,s);
            	}


 ::maglev::MagLevArray MagLevArray_obj::create(){
            	HX_GC_STACKFRAME(&_hx_pos_25210d59b9897ae1_422_create)
HXDLIN( 422)		return  ::maglev::MagLevArray_obj::__alloc( HX_CTX );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,create,return )

int MagLevArray_obj::getStaticType(){
            	HX_STACKFRAME(&_hx_pos_25210d59b9897ae1_457_getStaticType)
HXDLIN( 457)		return 5;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(MagLevArray_obj,getStaticType,return )


::hx::ObjectPtr< MagLevArray_obj > MagLevArray_obj::__new() {
	::hx::ObjectPtr< MagLevArray_obj > __this = new MagLevArray_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< MagLevArray_obj > MagLevArray_obj::__alloc(::hx::Ctx *_hx_ctx) {
	MagLevArray_obj *__this = (MagLevArray_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(MagLevArray_obj), true, "maglev.MagLevArray"));
	*(void **)__this = MagLevArray_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

MagLevArray_obj::MagLevArray_obj()
{
}

void MagLevArray_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(MagLevArray);
	HX_MARK_MEMBER_NAME(values,"values");
	HX_MARK_END_CLASS();
}

void MagLevArray_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(values,"values");
}

::hx::Val MagLevArray_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pop") ) { return ::hx::Val( pop_dyn() ); }
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		if (HX_FIELD_EQ(inName,"set") ) { return ::hx::Val( set_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"size") ) { return ::hx::Val( size_dyn() ); }
		if (HX_FIELD_EQ(inName,"push") ) { return ::hx::Val( push_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"shift") ) { return ::hx::Val( shift_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"values") ) { return ::hx::Val( values ); }
		if (HX_FIELD_EQ(inName,"toJson") ) { return ::hx::Val( toJson_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"unshift") ) { return ::hx::Val( unshift_dyn() ); }
		if (HX_FIELD_EQ(inName,"reverse") ) { return ::hx::Val( reverse_dyn() ); }
		if (HX_FIELD_EQ(inName,"getType") ) { return ::hx::Val( getType_dyn() ); }
		if (HX_FIELD_EQ(inName,"isEqual") ) { return ::hx::Val( isEqual_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool MagLevArray_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"create") ) { outValue = create_dyn(); return true; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"getStaticType") ) { outValue = getStaticType_dyn(); return true; }
	}
	return false;
}

::hx::Val MagLevArray_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"values") ) { values=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void MagLevArray_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("values",e2,03,b7,4f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo MagLevArray_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /* ::Array< ::Dynamic> */ ,(int)offsetof(MagLevArray_obj,values),HX_("values",e2,03,b7,4f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *MagLevArray_obj_sStaticStorageInfo = 0;
#endif

static ::String MagLevArray_obj_sMemberFields[] = {
	HX_("values",e2,03,b7,4f),
	HX_("size",c1,a0,53,4c),
	HX_("pop",91,5d,55,00),
	HX_("push",da,11,61,4a),
	HX_("shift",82,ec,22,7c),
	HX_("unshift",89,e3,b3,78),
	HX_("reverse",22,39,fc,1a),
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("getType",70,a2,8b,1f),
	HX_("isEqual",6a,73,08,0f),
	HX_("toJson",43,ad,21,7c),
	::String(null()) };

::hx::Class MagLevArray_obj::__mClass;

static ::String MagLevArray_obj_sStaticFields[] = {
	HX_("create",fc,66,0f,7c),
	HX_("getStaticType",be,46,27,0b),
	::String(null())
};

void MagLevArray_obj::__register()
{
	MagLevArray_obj _hx_dummy;
	MagLevArray_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("maglev.MagLevArray",cb,c2,02,ff);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &MagLevArray_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(MagLevArray_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(MagLevArray_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< MagLevArray_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = MagLevArray_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = MagLevArray_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace maglev
