// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_cpp_Finalizable
#include <cpp/Finalizable.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_08daad35fae38b7e_32_new,"cpp.Finalizable","new",0x5cbe4a08,"cpp.Finalizable.new","/opt/haxe/std/cpp/Finalizable.hx",32,0x580d3ef3)
HX_LOCAL_STACK_FRAME(_hx_pos_08daad35fae38b7e_35_finalize,"cpp.Finalizable","finalize",0xb32dcaf6,"cpp.Finalizable.finalize","/opt/haxe/std/cpp/Finalizable.hx",35,0x580d3ef3)
namespace cpp{

void Finalizable_obj::__construct(::hx::Null< bool >  __o_inPin){
            		bool inPin = __o_inPin.Default(false);
            	HX_STACKFRAME(&_hx_pos_08daad35fae38b7e_32_new)
HXDLIN(  32)		_hx_add_finalizable(::hx::ObjectPtr<OBJ_>(this),inPin);
            	}

Dynamic Finalizable_obj::__CreateEmpty() { return new Finalizable_obj; }

void *Finalizable_obj::_hx_vtable = 0;

Dynamic Finalizable_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Finalizable_obj > _hx_result = new Finalizable_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Finalizable_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x5b6e46de;
}

void Finalizable_obj::finalize(){
            	HX_STACKFRAME(&_hx_pos_08daad35fae38b7e_35_finalize)
            	}


HX_DEFINE_DYNAMIC_FUNC0(Finalizable_obj,finalize,(void))


Finalizable_obj::Finalizable_obj()
{
}

::hx::Val Finalizable_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 8:
		if (HX_FIELD_EQ(inName,"finalize") ) { return ::hx::Val( finalize_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Finalizable_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Finalizable_obj_sStaticStorageInfo = 0;
#endif

static ::String Finalizable_obj_sMemberFields[] = {
	HX_("finalize",9e,45,3a,f5),
	::String(null()) };

::hx::Class Finalizable_obj::__mClass;

void Finalizable_obj::__register()
{
	Finalizable_obj _hx_dummy;
	Finalizable_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("cpp.Finalizable",16,e6,c6,8e);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Finalizable_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Finalizable_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Finalizable_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Finalizable_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace cpp
