// Generated by Haxe 4.1.1
#include <hxcpp.h>

#ifndef INCLUDED_5f5af744d9ff5693
#define INCLUDED_5f5af744d9ff5693
#include "cpp/Pointer.h"
#endif
#ifndef INCLUDED_EReg
#include <maglev/EReg.h>
#endif
#ifndef INCLUDED_Std
#include <maglev/Std.h>
#endif
#ifndef INCLUDED_StringBuf
#include <maglev/StringBuf.h>
#endif
#ifndef INCLUDED_StringTools
#include <maglev/StringTools.h>
#endif
#ifndef INCLUDED_haxe_SysTools
#include <maglev/haxe/SysTools.h>
#endif
#ifndef INCLUDED_haxe_iterators_StringIterator
#include <maglev/haxe/iterators/StringIterator.h>
#endif
#ifndef INCLUDED_haxe_iterators_StringKeyValueIterator
#include <maglev/haxe/iterators/StringKeyValueIterator.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_50_urlEncode,"StringTools","urlEncode",0x06afdce1,"StringTools.urlEncode","/opt/haxe/std/StringTools.hx",50,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_118_urlDecode,"StringTools","urlDecode",0x71b947f9,"StringTools.urlDecode","/opt/haxe/std/StringTools.hx",118,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_158_htmlEscape,"StringTools","htmlEscape",0x0e1a5dd0,"StringTools.htmlEscape","/opt/haxe/std/StringTools.hx",158,0x7f83095e)
static const ::String _hx_array_data_0363db6a_4[] = {
	HX_("&quot;",2c,d9,81,8f),
};
static const ::String _hx_array_data_0363db6a_5[] = {
	HX_("&amp;",dd,d4,aa,21),
};
static const ::String _hx_array_data_0363db6a_6[] = {
	HX_("&#039;",62,26,77,78),
};
static const ::String _hx_array_data_0363db6a_7[] = {
	HX_("&lt;",4d,74,70,19),
};
static const ::String _hx_array_data_0363db6a_8[] = {
	HX_("&gt;",08,a9,6c,19),
};
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_194_htmlUnescape,"StringTools","htmlUnescape",0x7457fea9,"StringTools.htmlUnescape","/opt/haxe/std/StringTools.hx",194,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_212_contains,"StringTools","contains",0x5f7a9fa3,"StringTools.contains","/opt/haxe/std/StringTools.hx",212,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_222_startsWith,"StringTools","startsWith",0x5f4e6efb,"StringTools.startsWith","/opt/haxe/std/StringTools.hx",222,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_252_endsWith,"StringTools","endsWith",0x0eb5bfe2,"StringTools.endsWith","/opt/haxe/std/StringTools.hx",252,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_279_isSpace,"StringTools","isSpace",0xe0290778,"StringTools.isSpace","/opt/haxe/std/StringTools.hx",279,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_297_ltrim,"StringTools","ltrim",0x24d2234a,"StringTools.ltrim","/opt/haxe/std/StringTools.hx",297,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_322_rtrim,"StringTools","rtrim",0x99399e50,"StringTools.rtrim","/opt/haxe/std/StringTools.hx",322,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_350_trim,"StringTools","trim",0x2908d066,"StringTools.trim","/opt/haxe/std/StringTools.hx",350,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_366_lpad,"StringTools","lpad",0x23bd8feb,"StringTools.lpad","/opt/haxe/std/StringTools.hx",366,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_391_rpad,"StringTools","rpad",0x27b4d7a5,"StringTools.rpad","/opt/haxe/std/StringTools.hx",391,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_425_replace,"StringTools","replace",0x6d651f30,"StringTools.replace","/opt/haxe/std/StringTools.hx",425,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_435_hex,"StringTools","hex",0xd91debd7,"StringTools.hex","/opt/haxe/std/StringTools.hx",435,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_481_fastCodeAt,"StringTools","fastCodeAt",0x6fd011c0,"StringTools.fastCodeAt","/opt/haxe/std/StringTools.hx",481,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_513_iterator,"StringTools","iterator",0xc6998f72,"StringTools.iterator","/opt/haxe/std/StringTools.hx",513,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_524_keyValueIterator,"StringTools","keyValueIterator",0xeab536e4,"StringTools.keyValueIterator","/opt/haxe/std/StringTools.hx",524,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_532_isEof,"StringTools","isEof",0x69d30eee,"StringTools.isEof","/opt/haxe/std/StringTools.hx",532,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_552_quoteUnixArg,"StringTools","quoteUnixArg",0xc59dac56,"StringTools.quoteUnixArg","/opt/haxe/std/StringTools.hx",552,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_578_quoteWinArg,"StringTools","quoteWinArg",0x7e16b8f2,"StringTools.quoteWinArg","/opt/haxe/std/StringTools.hx",578,0x7f83095e)
static const ::String _hx_array_data_0363db6a_37[] = {
	HX_("\"",22,00,00,00),
};
static const ::String _hx_array_data_0363db6a_38[] = {
	HX_("\\\"",46,50,00,00),
};
static const ::String _hx_array_data_0363db6a_39[] = {
	HX_("\\",5c,00,00,00),
};
static const ::String _hx_array_data_0363db6a_40[] = {
	HX_("\"",22,00,00,00),
};
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_594_utf16CodePointAt,"StringTools","utf16CodePointAt",0x243cd4ce,"StringTools.utf16CodePointAt","/opt/haxe/std/StringTools.hx",594,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_560_boot,"StringTools","boot",0x1d20b7b6,"StringTools.boot","/opt/haxe/std/StringTools.hx",560,0x7f83095e)
HX_LOCAL_STACK_FRAME(_hx_pos_13872a0344302f80_592_boot,"StringTools","boot",0x1d20b7b6,"StringTools.boot","/opt/haxe/std/StringTools.hx",592,0x7f83095e)

void StringTools_obj::__construct() { }

Dynamic StringTools_obj::__CreateEmpty() { return new StringTools_obj; }

void *StringTools_obj::_hx_vtable = 0;

Dynamic StringTools_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< StringTools_obj > _hx_result = new StringTools_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool StringTools_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x084f186e;
}

::String StringTools_obj::urlEncode(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_50_urlEncode)
HXDLIN(  50)		return ( (::String)(s.__URLEncode()) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,urlEncode,return )

::String StringTools_obj::urlDecode(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_118_urlDecode)
HXDLIN( 118)		return ( (::String)(s.__URLDecode()) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,urlDecode,return )

::String StringTools_obj::htmlEscape(::String s, ::Dynamic quotes){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_158_htmlEscape)
HXLINE( 159)		 ::StringBuf buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 160)		{
HXLINE( 160)			int _g_offset = 0;
HXDLIN( 160)			::String _g_s = s;
HXDLIN( 160)			while((_g_offset < _g_s.length)){
HXLINE( 160)				::String s = _g_s;
HXDLIN( 160)				_g_offset = (_g_offset + 1);
HXDLIN( 160)				int index = (_g_offset - 1);
HXDLIN( 160)				int c = s.cca(index);
HXDLIN( 160)				bool _hx_tmp;
HXDLIN( 160)				if ((c >= 55296)) {
HXLINE( 160)					_hx_tmp = (c <= 56319);
            				}
            				else {
HXLINE( 160)					_hx_tmp = false;
            				}
HXDLIN( 160)				if (_hx_tmp) {
HXLINE( 597)					c = (((c - 55232) << 10) | (s.cca((index + 1)) & 1023));
            				}
HXLINE( 160)				int c1 = c;
HXDLIN( 160)				if ((c1 >= 65536)) {
HXLINE( 160)					_g_offset = (_g_offset + 1);
            				}
HXDLIN( 160)				int code = c1;
HXLINE( 161)				switch((int)(code)){
            					case (int)34: {
HXLINE( 168)						if (( (bool)(quotes) )) {
HXLINE( 169)							if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 169)								buf->flush();
            							}
HXDLIN( 169)							if (::hx::IsNull( buf->b )) {
HXLINE( 169)								buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_4,1);
            							}
            							else {
HXLINE( 169)								buf->b->push(HX_("&quot;",2c,d9,81,8f));
            							}
            						}
            						else {
HXLINE( 173)							if ((code >= 127)) {
HXLINE( 173)								::String x = ::String::fromCharCode(code);
HXDLIN( 173)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 173)									buf->flush();
            								}
HXDLIN( 173)								if (::hx::IsNull( buf->b )) {
HXLINE( 173)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            								}
            								else {
HXLINE( 173)									::Array< ::String > buf1 = buf->b;
HXDLIN( 173)									buf1->push(::Std_obj::string(x));
            								}
            							}
            							else {
HXLINE( 173)								if (::hx::IsNull( buf->charBuf )) {
HXLINE( 173)									buf->charBuf = ::Array_obj< char >::__new();
            								}
HXDLIN( 173)								buf->charBuf->push(code);
            							}
            						}
            					}
            					break;
            					case (int)38: {
HXLINE( 163)						if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 163)							buf->flush();
            						}
HXDLIN( 163)						if (::hx::IsNull( buf->b )) {
HXLINE( 163)							buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_5,1);
            						}
            						else {
HXLINE( 163)							buf->b->push(HX_("&amp;",dd,d4,aa,21));
            						}
            					}
            					break;
            					case (int)39: {
HXLINE( 170)						if (( (bool)(quotes) )) {
HXLINE( 171)							if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 171)								buf->flush();
            							}
HXDLIN( 171)							if (::hx::IsNull( buf->b )) {
HXLINE( 171)								buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_6,1);
            							}
            							else {
HXLINE( 171)								buf->b->push(HX_("&#039;",62,26,77,78));
            							}
            						}
            						else {
HXLINE( 173)							if ((code >= 127)) {
HXLINE( 173)								::String x = ::String::fromCharCode(code);
HXDLIN( 173)								if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 173)									buf->flush();
            								}
HXDLIN( 173)								if (::hx::IsNull( buf->b )) {
HXLINE( 173)									buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            								}
            								else {
HXLINE( 173)									::Array< ::String > buf1 = buf->b;
HXDLIN( 173)									buf1->push(::Std_obj::string(x));
            								}
            							}
            							else {
HXLINE( 173)								if (::hx::IsNull( buf->charBuf )) {
HXLINE( 173)									buf->charBuf = ::Array_obj< char >::__new();
            								}
HXDLIN( 173)								buf->charBuf->push(code);
            							}
            						}
            					}
            					break;
            					case (int)60: {
HXLINE( 165)						if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 165)							buf->flush();
            						}
HXDLIN( 165)						if (::hx::IsNull( buf->b )) {
HXLINE( 165)							buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_7,1);
            						}
            						else {
HXLINE( 165)							buf->b->push(HX_("&lt;",4d,74,70,19));
            						}
            					}
            					break;
            					case (int)62: {
HXLINE( 167)						if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 167)							buf->flush();
            						}
HXDLIN( 167)						if (::hx::IsNull( buf->b )) {
HXLINE( 167)							buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_8,1);
            						}
            						else {
HXLINE( 167)							buf->b->push(HX_("&gt;",08,a9,6c,19));
            						}
            					}
            					break;
            					default:{
HXLINE( 173)						if ((code >= 127)) {
HXLINE( 173)							::String x = ::String::fromCharCode(code);
HXDLIN( 173)							if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 173)								buf->flush();
            							}
HXDLIN( 173)							if (::hx::IsNull( buf->b )) {
HXLINE( 173)								buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            							}
            							else {
HXLINE( 173)								::Array< ::String > buf1 = buf->b;
HXDLIN( 173)								buf1->push(::Std_obj::string(x));
            							}
            						}
            						else {
HXLINE( 173)							if (::hx::IsNull( buf->charBuf )) {
HXLINE( 173)								buf->charBuf = ::Array_obj< char >::__new();
            							}
HXDLIN( 173)							buf->charBuf->push(code);
            						}
            					}
            				}
            			}
            		}
HXLINE( 176)		return buf->toString();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,htmlEscape,return )

::String StringTools_obj::htmlUnescape(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_194_htmlUnescape)
HXDLIN( 194)		return s.split(HX_("&gt;",08,a9,6c,19))->join(HX_(">",3e,00,00,00)).split(HX_("&lt;",4d,74,70,19))->join(HX_("<",3c,00,00,00)).split(HX_("&quot;",2c,d9,81,8f))->join(HX_("\"",22,00,00,00)).split(HX_("&#039;",62,26,77,78))->join(HX_("'",27,00,00,00)).split(HX_("&amp;",dd,d4,aa,21))->join(HX_("&",26,00,00,00));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,htmlUnescape,return )

bool StringTools_obj::contains(::String s,::String value){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_212_contains)
HXDLIN( 212)		return (s.indexOf(value,null()) != -1);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,contains,return )

bool StringTools_obj::startsWith(::String s,::String start){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_222_startsWith)
HXLINE( 228)		if ((s.length < start.length)) {
HXLINE( 229)			return false;
            		}
HXLINE( 230)		::cpp::Pointer< char > p0 = cpp::Pointer_obj::fromPointer(s.c_str());
HXLINE( 231)		::cpp::Pointer< char > p1 = cpp::Pointer_obj::fromPointer(start.c_str());
HXLINE( 232)		{
HXLINE( 232)			int _g = 0;
HXDLIN( 232)			int _g1 = start.length;
HXDLIN( 232)			while((_g < _g1)){
HXLINE( 232)				_g = (_g + 1);
HXDLIN( 232)				int i = (_g - 1);
HXLINE( 233)				char & _hx_tmp = p0->at(i);
HXDLIN( 233)				char & _hx_tmp1 = p1->at(i);
HXDLIN( 233)				if (::hx::IsNotEq( _hx_tmp,_hx_tmp1 )) {
HXLINE( 234)					return false;
            				}
            			}
            		}
HXLINE( 235)		return true;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,startsWith,return )

bool StringTools_obj::endsWith(::String s,::String end){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_252_endsWith)
HXLINE( 264)		int elen = end.length;
HXLINE( 265)		int slen = s.length;
HXLINE( 266)		if ((slen >= elen)) {
HXLINE( 266)			return (s.indexOf(end,(slen - elen)) == (slen - elen));
            		}
            		else {
HXLINE( 266)			return false;
            		}
HXDLIN( 266)		return false;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,endsWith,return )

bool StringTools_obj::isSpace(::String s,int pos){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_279_isSpace)
HXLINE( 284)		 ::Dynamic c = s.charCodeAt(pos);
HXLINE( 285)		bool _hx_tmp;
HXDLIN( 285)		if (::hx::IsGreater( c,8 )) {
HXLINE( 285)			_hx_tmp = ::hx::IsLess( c,14 );
            		}
            		else {
HXLINE( 285)			_hx_tmp = false;
            		}
HXDLIN( 285)		if (!(_hx_tmp)) {
HXLINE( 285)			return ::hx::IsEq( c,32 );
            		}
            		else {
HXLINE( 285)			return true;
            		}
HXDLIN( 285)		return false;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,isSpace,return )

::String StringTools_obj::ltrim(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_297_ltrim)
HXLINE( 301)		int l = s.length;
HXLINE( 302)		int r = 0;
HXLINE( 303)		while(true){
HXLINE( 303)			bool _hx_tmp;
HXDLIN( 303)			if ((r < l)) {
HXLINE( 303)				_hx_tmp = ::StringTools_obj::isSpace(s,r);
            			}
            			else {
HXLINE( 303)				_hx_tmp = false;
            			}
HXDLIN( 303)			if (!(_hx_tmp)) {
HXLINE( 303)				goto _hx_goto_15;
            			}
HXLINE( 304)			r = (r + 1);
            		}
            		_hx_goto_15:;
HXLINE( 306)		if ((r > 0)) {
HXLINE( 307)			return s.substr(r,(l - r));
            		}
            		else {
HXLINE( 309)			return s;
            		}
HXLINE( 306)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,ltrim,return )

::String StringTools_obj::rtrim(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_322_rtrim)
HXLINE( 326)		int l = s.length;
HXLINE( 327)		int r = 0;
HXLINE( 328)		while(true){
HXLINE( 328)			bool _hx_tmp;
HXDLIN( 328)			if ((r < l)) {
HXLINE( 328)				_hx_tmp = ::StringTools_obj::isSpace(s,((l - r) - 1));
            			}
            			else {
HXLINE( 328)				_hx_tmp = false;
            			}
HXDLIN( 328)			if (!(_hx_tmp)) {
HXLINE( 328)				goto _hx_goto_17;
            			}
HXLINE( 329)			r = (r + 1);
            		}
            		_hx_goto_17:;
HXLINE( 331)		if ((r > 0)) {
HXLINE( 332)			return s.substr(0,(l - r));
            		}
            		else {
HXLINE( 334)			return s;
            		}
HXLINE( 331)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,rtrim,return )

::String StringTools_obj::trim(::String s){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_350_trim)
HXDLIN( 350)		return ::StringTools_obj::ltrim(::StringTools_obj::rtrim(s));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,trim,return )

::String StringTools_obj::lpad(::String s,::String c,int l){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_366_lpad)
HXLINE( 367)		if ((c.length <= 0)) {
HXLINE( 368)			return s;
            		}
HXLINE( 370)		 ::StringBuf buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 371)		l = (l - s.length);
HXLINE( 372)		while((buf->get_length() < l)){
HXLINE( 373)			if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 373)				buf->flush();
            			}
HXDLIN( 373)			if (::hx::IsNull( buf->b )) {
HXLINE( 373)				buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(c));
            			}
            			else {
HXLINE( 373)				::Array< ::String > buf1 = buf->b;
HXDLIN( 373)				buf1->push(::Std_obj::string(c));
            			}
            		}
HXLINE( 375)		{
HXLINE( 375)			if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 375)				buf->flush();
            			}
HXDLIN( 375)			if (::hx::IsNull( buf->b )) {
HXLINE( 375)				buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(s));
            			}
            			else {
HXLINE( 375)				::Array< ::String > buf1 = buf->b;
HXDLIN( 375)				buf1->push(::Std_obj::string(s));
            			}
            		}
HXLINE( 376)		return buf->toString();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(StringTools_obj,lpad,return )

::String StringTools_obj::rpad(::String s,::String c,int l){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_391_rpad)
HXLINE( 392)		if ((c.length <= 0)) {
HXLINE( 393)			return s;
            		}
HXLINE( 395)		 ::StringBuf buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXLINE( 396)		{
HXLINE( 396)			if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 396)				buf->flush();
            			}
HXDLIN( 396)			if (::hx::IsNull( buf->b )) {
HXLINE( 396)				buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(s));
            			}
            			else {
HXLINE( 396)				::Array< ::String > buf1 = buf->b;
HXDLIN( 396)				buf1->push(::Std_obj::string(s));
            			}
            		}
HXLINE( 397)		while((buf->get_length() < l)){
HXLINE( 398)			if (::hx::IsNotNull( buf->charBuf )) {
HXLINE( 398)				buf->flush();
            			}
HXDLIN( 398)			if (::hx::IsNull( buf->b )) {
HXLINE( 398)				buf->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(c));
            			}
            			else {
HXLINE( 398)				::Array< ::String > buf1 = buf->b;
HXDLIN( 398)				buf1->push(::Std_obj::string(c));
            			}
            		}
HXLINE( 400)		return buf->toString();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(StringTools_obj,rpad,return )

::String StringTools_obj::replace(::String s,::String sub,::String by){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_425_replace)
HXDLIN( 425)		return s.split(sub)->join(by);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(StringTools_obj,replace,return )

::String StringTools_obj::hex(int n, ::Dynamic digits){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_435_hex)
HXLINE( 441)		::String s = HX_("",00,00,00,00);
HXLINE( 442)		::String hexChars = HX_("0123456789ABCDEF",68,2a,58,a2);
HXLINE( 443)		while(true){
HXLINE( 444)			s = (hexChars.charAt((n & 15)) + s);
HXLINE( 445)			n = ::hx::UShr(n,4);
HXLINE( 443)			if (!((n > 0))) {
HXLINE( 443)				goto _hx_goto_25;
            			}
            		}
            		_hx_goto_25:;
HXLINE( 456)		if (::hx::IsNotNull( digits )) {
HXLINE( 457)			while(::hx::IsLess( s.length,digits )){
HXLINE( 458)				s = (HX_("0",30,00,00,00) + s);
            			}
            		}
HXLINE( 460)		return s;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,hex,return )

int StringTools_obj::fastCodeAt(::String s,int index){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_481_fastCodeAt)
HXDLIN( 481)		return s.cca(index);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,fastCodeAt,return )

 ::haxe::iterators::StringIterator StringTools_obj::iterator(::String s){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_513_iterator)
HXDLIN( 513)		return  ::haxe::iterators::StringIterator_obj::__alloc( HX_CTX ,s);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,iterator,return )

 ::haxe::iterators::StringKeyValueIterator StringTools_obj::keyValueIterator(::String s){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_524_keyValueIterator)
HXDLIN( 524)		return  ::haxe::iterators::StringKeyValueIterator_obj::__alloc( HX_CTX ,s);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,keyValueIterator,return )

bool StringTools_obj::isEof(int c){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_532_isEof)
HXDLIN( 532)		return (c == 0);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,isEof,return )

::String StringTools_obj::quoteUnixArg(::String argument){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_552_quoteUnixArg)
HXDLIN( 552)		if ((argument == HX_("",00,00,00,00))) {
HXDLIN( 552)			return HX_("''",20,22,00,00);
            		}
            		else {
HXDLIN( 552)			if (!( ::EReg_obj::__alloc( HX_CTX ,HX_("[^a-zA-Z0-9_@%+=:,./-]",80,28,a0,8d),HX_("",00,00,00,00))->match(argument))) {
HXDLIN( 552)				return argument;
            			}
            			else {
HXDLIN( 552)				return ((HX_("'",27,00,00,00) + ::StringTools_obj::replace(argument,HX_("'",27,00,00,00),HX_("'\"'\"'",71,96,37,8b))) + HX_("'",27,00,00,00));
            			}
            		}
HXDLIN( 552)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(StringTools_obj,quoteUnixArg,return )

::Array< int > StringTools_obj::winMetaCharacters;

::String StringTools_obj::quoteWinArg(::String argument,bool escapeMetaCharacters){
            	HX_GC_STACKFRAME(&_hx_pos_13872a0344302f80_578_quoteWinArg)
HXDLIN( 578)		::String argument1 = argument;
HXDLIN( 578)		if (!( ::EReg_obj::__alloc( HX_CTX ,HX_("^[^ \t\\\\\"]+$",fe,85,ca,95),HX_("",00,00,00,00))->match(argument1))) {
HXDLIN( 578)			 ::StringBuf result =  ::StringBuf_obj::__alloc( HX_CTX );
HXDLIN( 578)			bool needquote;
HXDLIN( 578)			bool needquote1;
HXDLIN( 578)			if ((argument1.indexOf(HX_(" ",20,00,00,00),null()) == -1)) {
HXDLIN( 578)				needquote1 = (argument1.indexOf(HX_("\t",09,00,00,00),null()) != -1);
            			}
            			else {
HXDLIN( 578)				needquote1 = true;
            			}
HXDLIN( 578)			if (!(needquote1)) {
HXDLIN( 578)				needquote = (argument1 == HX_("",00,00,00,00));
            			}
            			else {
HXDLIN( 578)				needquote = true;
            			}
HXDLIN( 578)			if (needquote) {
HXDLIN( 578)				if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)					result->flush();
            				}
HXDLIN( 578)				if (::hx::IsNull( result->b )) {
HXDLIN( 578)					result->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_37,1);
            				}
            				else {
HXDLIN( 578)					result->b->push(HX_("\"",22,00,00,00));
            				}
            			}
HXDLIN( 578)			 ::StringBuf bs_buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXDLIN( 578)			{
HXDLIN( 578)				int _g = 0;
HXDLIN( 578)				int _g1 = argument1.length;
HXDLIN( 578)				while((_g < _g1)){
HXDLIN( 578)					_g = (_g + 1);
HXDLIN( 578)					int i = (_g - 1);
HXDLIN( 578)					{
HXDLIN( 578)						 ::Dynamic _g1 = argument1.charCodeAt(i);
HXDLIN( 578)						if (::hx::IsNull( _g1 )) {
HXDLIN( 578)							 ::Dynamic c = _g1;
HXDLIN( 578)							{
HXDLIN( 578)								if ((bs_buf->get_length() > 0)) {
HXDLIN( 578)									{
HXDLIN( 578)										::String x = bs_buf->toString();
HXDLIN( 578)										if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)											result->flush();
            										}
HXDLIN( 578)										if (::hx::IsNull( result->b )) {
HXDLIN( 578)											result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            										}
            										else {
HXDLIN( 578)											::Array< ::String > result1 = result->b;
HXDLIN( 578)											result1->push(::Std_obj::string(x));
            										}
            									}
HXDLIN( 578)									bs_buf =  ::StringBuf_obj::__alloc( HX_CTX );
            								}
HXDLIN( 578)								{
HXDLIN( 578)									int c1 = ( (int)(c) );
HXDLIN( 578)									if ((c1 >= 127)) {
HXDLIN( 578)										::String x = ::String::fromCharCode(c1);
HXDLIN( 578)										if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)											result->flush();
            										}
HXDLIN( 578)										if (::hx::IsNull( result->b )) {
HXDLIN( 578)											result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            										}
            										else {
HXDLIN( 578)											::Array< ::String > result1 = result->b;
HXDLIN( 578)											result1->push(::Std_obj::string(x));
            										}
            									}
            									else {
HXDLIN( 578)										if (::hx::IsNull( result->charBuf )) {
HXDLIN( 578)											result->charBuf = ::Array_obj< char >::__new();
            										}
HXDLIN( 578)										result->charBuf->push(c1);
            									}
            								}
            							}
            						}
            						else {
HXDLIN( 578)							 ::Dynamic _hx_switch_0 = _g1;
            							if (  (_hx_switch_0==34) ){
HXDLIN( 578)								::String bs = bs_buf->toString();
HXDLIN( 578)								{
HXDLIN( 578)									if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)										result->flush();
            									}
HXDLIN( 578)									if (::hx::IsNull( result->b )) {
HXDLIN( 578)										result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(bs));
            									}
            									else {
HXDLIN( 578)										::Array< ::String > result1 = result->b;
HXDLIN( 578)										result1->push(::Std_obj::string(bs));
            									}
            								}
HXDLIN( 578)								{
HXDLIN( 578)									if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)										result->flush();
            									}
HXDLIN( 578)									if (::hx::IsNull( result->b )) {
HXDLIN( 578)										result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(bs));
            									}
            									else {
HXDLIN( 578)										::Array< ::String > result1 = result->b;
HXDLIN( 578)										result1->push(::Std_obj::string(bs));
            									}
            								}
HXDLIN( 578)								bs_buf =  ::StringBuf_obj::__alloc( HX_CTX );
HXDLIN( 578)								{
HXDLIN( 578)									if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)										result->flush();
            									}
HXDLIN( 578)									if (::hx::IsNull( result->b )) {
HXDLIN( 578)										result->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_38,1);
            									}
            									else {
HXDLIN( 578)										result->b->push(HX_("\\\"",46,50,00,00));
            									}
            								}
HXDLIN( 578)								goto _hx_goto_34;
            							}
            							if (  (_hx_switch_0==92) ){
HXDLIN( 578)								if (::hx::IsNotNull( bs_buf->charBuf )) {
HXDLIN( 578)									bs_buf->flush();
            								}
HXDLIN( 578)								if (::hx::IsNull( bs_buf->b )) {
HXDLIN( 578)									bs_buf->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_39,1);
            								}
            								else {
HXDLIN( 578)									bs_buf->b->push(HX_("\\",5c,00,00,00));
            								}
HXDLIN( 578)								goto _hx_goto_34;
            							}
            							/* default */{
HXDLIN( 578)								 ::Dynamic c = _g1;
HXDLIN( 578)								{
HXDLIN( 578)									if ((bs_buf->get_length() > 0)) {
HXDLIN( 578)										{
HXDLIN( 578)											::String x = bs_buf->toString();
HXDLIN( 578)											if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)												result->flush();
            											}
HXDLIN( 578)											if (::hx::IsNull( result->b )) {
HXDLIN( 578)												result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            											}
            											else {
HXDLIN( 578)												::Array< ::String > result1 = result->b;
HXDLIN( 578)												result1->push(::Std_obj::string(x));
            											}
            										}
HXDLIN( 578)										bs_buf =  ::StringBuf_obj::__alloc( HX_CTX );
            									}
HXDLIN( 578)									{
HXDLIN( 578)										int c1 = ( (int)(c) );
HXDLIN( 578)										if ((c1 >= 127)) {
HXDLIN( 578)											::String x = ::String::fromCharCode(c1);
HXDLIN( 578)											if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)												result->flush();
            											}
HXDLIN( 578)											if (::hx::IsNull( result->b )) {
HXDLIN( 578)												result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            											}
            											else {
HXDLIN( 578)												::Array< ::String > result1 = result->b;
HXDLIN( 578)												result1->push(::Std_obj::string(x));
            											}
            										}
            										else {
HXDLIN( 578)											if (::hx::IsNull( result->charBuf )) {
HXDLIN( 578)												result->charBuf = ::Array_obj< char >::__new();
            											}
HXDLIN( 578)											result->charBuf->push(c1);
            										}
            									}
            								}
            							}
            							_hx_goto_34:;
            						}
            					}
            				}
            			}
HXDLIN( 578)			{
HXDLIN( 578)				::String x = bs_buf->toString();
HXDLIN( 578)				if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)					result->flush();
            				}
HXDLIN( 578)				if (::hx::IsNull( result->b )) {
HXDLIN( 578)					result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            				}
            				else {
HXDLIN( 578)					::Array< ::String > result1 = result->b;
HXDLIN( 578)					result1->push(::Std_obj::string(x));
            				}
            			}
HXDLIN( 578)			if (needquote) {
HXDLIN( 578)				{
HXDLIN( 578)					::String x = bs_buf->toString();
HXDLIN( 578)					if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)						result->flush();
            					}
HXDLIN( 578)					if (::hx::IsNull( result->b )) {
HXDLIN( 578)						result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            					}
            					else {
HXDLIN( 578)						::Array< ::String > result1 = result->b;
HXDLIN( 578)						result1->push(::Std_obj::string(x));
            					}
            				}
HXDLIN( 578)				{
HXDLIN( 578)					if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)						result->flush();
            					}
HXDLIN( 578)					if (::hx::IsNull( result->b )) {
HXDLIN( 578)						result->b = ::Array_obj< ::String >::fromData( _hx_array_data_0363db6a_40,1);
            					}
            					else {
HXDLIN( 578)						result->b->push(HX_("\"",22,00,00,00));
            					}
            				}
            			}
HXDLIN( 578)			argument1 = result->toString();
            		}
HXDLIN( 578)		if (escapeMetaCharacters) {
HXDLIN( 578)			 ::StringBuf result =  ::StringBuf_obj::__alloc( HX_CTX );
HXDLIN( 578)			{
HXDLIN( 578)				int _g = 0;
HXDLIN( 578)				int _g1 = argument1.length;
HXDLIN( 578)				while((_g < _g1)){
HXDLIN( 578)					_g = (_g + 1);
HXDLIN( 578)					int i = (_g - 1);
HXDLIN( 578)					 ::Dynamic c = argument1.charCodeAt(i);
HXDLIN( 578)					if ((::haxe::SysTools_obj::winMetaCharacters->indexOf(c,null()) >= 0)) {
HXDLIN( 578)						if (::hx::IsNull( result->charBuf )) {
HXDLIN( 578)							result->charBuf = ::Array_obj< char >::__new();
            						}
HXDLIN( 578)						result->charBuf->push(94);
            					}
HXDLIN( 578)					{
HXDLIN( 578)						int c1 = ( (int)(c) );
HXDLIN( 578)						if ((c1 >= 127)) {
HXDLIN( 578)							::String x = ::String::fromCharCode(c1);
HXDLIN( 578)							if (::hx::IsNotNull( result->charBuf )) {
HXDLIN( 578)								result->flush();
            							}
HXDLIN( 578)							if (::hx::IsNull( result->b )) {
HXDLIN( 578)								result->b = ::Array_obj< ::String >::__new(1)->init(0,::Std_obj::string(x));
            							}
            							else {
HXDLIN( 578)								::Array< ::String > result1 = result->b;
HXDLIN( 578)								result1->push(::Std_obj::string(x));
            							}
            						}
            						else {
HXDLIN( 578)							if (::hx::IsNull( result->charBuf )) {
HXDLIN( 578)								result->charBuf = ::Array_obj< char >::__new();
            							}
HXDLIN( 578)							result->charBuf->push(c1);
            						}
            					}
            				}
            			}
HXDLIN( 578)			return result->toString();
            		}
            		else {
HXDLIN( 578)			return argument1;
            		}
HXDLIN( 578)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,quoteWinArg,return )

int StringTools_obj::MIN_SURROGATE_CODE_POINT;

int StringTools_obj::utf16CodePointAt(::String s,int index){
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_594_utf16CodePointAt)
HXLINE( 595)		int c = s.cca(index);
HXLINE( 596)		bool _hx_tmp;
HXDLIN( 596)		if ((c >= 55296)) {
HXLINE( 596)			_hx_tmp = (c <= 56319);
            		}
            		else {
HXLINE( 596)			_hx_tmp = false;
            		}
HXDLIN( 596)		if (_hx_tmp) {
HXLINE( 597)			c = (((c - 55232) << 10) | (s.cca((index + 1)) & 1023));
            		}
HXLINE( 599)		return c;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(StringTools_obj,utf16CodePointAt,return )


StringTools_obj::StringTools_obj()
{
}

bool StringTools_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"hex") ) { outValue = hex_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"trim") ) { outValue = trim_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"lpad") ) { outValue = lpad_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"rpad") ) { outValue = rpad_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"ltrim") ) { outValue = ltrim_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"rtrim") ) { outValue = rtrim_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"isEof") ) { outValue = isEof_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"isSpace") ) { outValue = isSpace_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"replace") ) { outValue = replace_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"contains") ) { outValue = contains_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"endsWith") ) { outValue = endsWith_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"iterator") ) { outValue = iterator_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"urlEncode") ) { outValue = urlEncode_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"urlDecode") ) { outValue = urlDecode_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"htmlEscape") ) { outValue = htmlEscape_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"startsWith") ) { outValue = startsWith_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"fastCodeAt") ) { outValue = fastCodeAt_dyn(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"quoteWinArg") ) { outValue = quoteWinArg_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"htmlUnescape") ) { outValue = htmlUnescape_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"quoteUnixArg") ) { outValue = quoteUnixArg_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"keyValueIterator") ) { outValue = keyValueIterator_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"utf16CodePointAt") ) { outValue = utf16CodePointAt_dyn(); return true; }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"winMetaCharacters") ) { outValue = ( winMetaCharacters ); return true; }
	}
	return false;
}

bool StringTools_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 17:
		if (HX_FIELD_EQ(inName,"winMetaCharacters") ) { winMetaCharacters=ioValue.Cast< ::Array< int > >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *StringTools_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo StringTools_obj_sStaticStorageInfo[] = {
	{::hx::fsObject /* ::Array< int > */ ,(void *) &StringTools_obj::winMetaCharacters,HX_("winMetaCharacters",0b,65,cd,94)},
	{::hx::fsInt,(void *) &StringTools_obj::MIN_SURROGATE_CODE_POINT,HX_("MIN_SURROGATE_CODE_POINT",f2,39,5a,0a)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void StringTools_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(StringTools_obj::winMetaCharacters,"winMetaCharacters");
	HX_MARK_MEMBER_NAME(StringTools_obj::MIN_SURROGATE_CODE_POINT,"MIN_SURROGATE_CODE_POINT");
};

#ifdef HXCPP_VISIT_ALLOCS
static void StringTools_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(StringTools_obj::winMetaCharacters,"winMetaCharacters");
	HX_VISIT_MEMBER_NAME(StringTools_obj::MIN_SURROGATE_CODE_POINT,"MIN_SURROGATE_CODE_POINT");
};

#endif

::hx::Class StringTools_obj::__mClass;

static ::String StringTools_obj_sStaticFields[] = {
	HX_("urlEncode",e5,4e,52,9a),
	HX_("urlDecode",fd,b9,5b,05),
	HX_("htmlEscape",4c,af,9b,a8),
	HX_("htmlUnescape",25,a7,ed,ae),
	HX_("contains",1f,5a,7b,2c),
	HX_("startsWith",77,c0,cf,f9),
	HX_("endsWith",5e,7a,b6,db),
	HX_("isSpace",7c,30,ec,1d),
	HX_("ltrim",4e,43,4a,7c),
	HX_("rtrim",54,be,b1,f0),
	HX_("trim",e2,9c,03,4d),
	HX_("lpad",67,5c,b8,47),
	HX_("rpad",21,a4,af,4b),
	HX_("replace",34,48,28,ab),
	HX_("hex",db,42,4f,00),
	HX_("fastCodeAt",3c,63,51,0a),
	HX_("iterator",ee,49,9a,93),
	HX_("keyValueIterator",60,cd,ee,4a),
	HX_("isEof",f2,2e,4b,c1),
	HX_("quoteUnixArg",d2,54,33,00),
	HX_("winMetaCharacters",0b,65,cd,94),
	HX_("quoteWinArg",f6,b3,bc,14),
	HX_("MIN_SURROGATE_CODE_POINT",f2,39,5a,0a),
	HX_("utf16CodePointAt",4a,6b,76,84),
	::String(null())
};

void StringTools_obj::__register()
{
	StringTools_obj _hx_dummy;
	StringTools_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("StringTools",6a,db,63,03);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &StringTools_obj::__GetStatic;
	__mClass->mSetStaticField = &StringTools_obj::__SetStatic;
	__mClass->mMarkFunc = StringTools_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(StringTools_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< StringTools_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = StringTools_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = StringTools_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = StringTools_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void StringTools_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_560_boot)
HXDLIN( 560)		winMetaCharacters = ::haxe::SysTools_obj::winMetaCharacters;
            	}
{
            	HX_STACKFRAME(&_hx_pos_13872a0344302f80_592_boot)
HXDLIN( 592)		MIN_SURROGATE_CODE_POINT = 65536;
            	}
}

